const PDFDocument = require('pdfkit');

/* ─── Shared header / footer helpers ──────────────────────────────────────── */

const drawHeader = (doc, department, title) => {
  doc.rect(0, 0, doc.page.width, 90).fill('#1e1b4b');
  doc.fillColor('white').font('Helvetica-Bold').fontSize(20)
     .text('RAMCO INSTITUTE OF TECHNOLOGY', 40, 20, { align: 'center' });
  doc.fontSize(12).font('Helvetica')
     .text('Rajapalayam, Virudhunagar District, Tamil Nadu', 40, 46, { align: 'center' });
  doc.fontSize(11)
     .text(`Department of ${department || 'Academic Affairs'}`, 40, 62, { align: 'center' });
  doc.fillColor('#1e1b4b').font('Helvetica-Bold').fontSize(15)
     .text(title, 40, 105, { align: 'center', underline: true });
};

const drawFooter = (doc) => {
  const y = doc.page.height - 55;
  doc.save().moveTo(40, y).lineTo(doc.page.width - 40, y)
     .strokeColor('#d1d5db').stroke().restore();
  doc.fillColor('#6b7280').fontSize(9)
     .text(`Generated by RIT CGPA Portal — ${new Date().toLocaleString('en-IN')}`, 40, y + 10, { align: 'center' });
};

/* ─── Column layout shared by single + batch GPA tables ──────────────────── */
// A4 content area: 40 → 555 (515 pt wide)
// Columns: # | Subject Code | Subject Name | Credits | Grade
const TABLE_COLS = [40, 68, 158, 378, 458];          // left edge of each col
const TABLE_COL_W = [26,  88, 218,  78,  94];         // width of each col
const TABLE_HEADERS = ['#', 'Subject Code', 'Subject Name', 'Credits', 'Grade'];
const ROW_H = 22;

/* ─── Single-student GPA PDF ─────────────────────────────────────────────── */
const buildGpaPdf = (record) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margins: { top: 40, bottom: 15, left: 40, right: 40 }, size: 'A4' });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    drawHeader(doc, record.department, 'Semester GPA Report');

    // ── Student info box ──
    doc.rect(40, 140, doc.page.width - 80, 60).fill('#f8fafc').stroke('#e2e8f0');
    doc.fillColor('#1e293b').font('Helvetica-Bold').fontSize(11).text('Student Details', 50, 148);
    doc.font('Helvetica').fontSize(10)
       .text(`Name: ${record.studentName}`, 50, 162)
       .text(`Register No: ${record.registerNo}`, 300, 162)
       .text(`Semester: ${record.semester}  |  Regulation: ${record.regulation || 'R2021'}  |  Dept: ${record.department}`, 50, 176);

    // ── Subjects table ──
    const tableTop = 215;

    // Header row
    doc.rect(40, tableTop, doc.page.width - 80, ROW_H).fill('#1e1b4b');
    doc.fillColor('white').font('Helvetica-Bold').fontSize(9);
    TABLE_HEADERS.forEach((h, i) =>
      doc.text(h, TABLE_COLS[i] + 3, tableTop + 7, { width: TABLE_COL_W[i], lineBreak: false })
    );

    // Data rows — only show subjects where a real grade was given
    let y = tableTop + ROW_H;
    let totalCredits = 0;
    const gradedSubjects = (record.subjects || []).filter(s => s.grade && s.grade.trim() !== '');
    gradedSubjects.forEach((s, idx) => {
      const bg = idx % 2 === 0 ? '#f8fafc' : 'white';
      doc.rect(40, y, doc.page.width - 80, ROW_H).fill(bg);
      doc.fillColor('#1e293b').font('Helvetica').fontSize(9);
      totalCredits += s.credits;
      const row = [idx + 1, s.subjectCode, s.subjectName, s.credits, s.grade];
      row.forEach((val, i) =>
        doc.text(String(val), TABLE_COLS[i] + 3, y + 7, { width: TABLE_COL_W[i], lineBreak: false })
      );
      y += ROW_H;
    });

    // ── Totals bar (Credits only) ──
    doc.rect(40, y, doc.page.width - 80, 22).fill('#e0e7ff');
    doc.fillColor('#1e1b4b').font('Helvetica-Bold').fontSize(10)
       .text(`Total Credits: ${totalCredits}`, 50, y + 6);
    y += 22;

    // ── GPA result badge ──
    y += 18;
    const cx = doc.page.width / 2;
    doc.roundedRect(cx - 80, y, 160, 58, 8).fill('#1e1b4b');
    doc.fillColor('white').font('Helvetica').fontSize(11)
       .text('Semester GPA', cx - 80, y + 9, { width: 160, align: 'center' });
    doc.font('Helvetica-Bold').fontSize(28).fillColor('#a5b4fc')
       .text(record.gpa.toFixed(2), cx - 80, y + 26, { width: 160, align: 'center' });

    drawFooter(doc);
    doc.end();
  });
};

/* ─── CGPA PDF ───────────────────────────────────────────────────────────── */
const buildCgpaPdf = (record) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margins: { top: 40, bottom: 15, left: 40, right: 40 }, size: 'A4' });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    drawHeader(doc, record.department, 'Cumulative CGPA Report');

    doc.rect(40, 140, doc.page.width - 80, 45).fill('#f8fafc').stroke('#e2e8f0');
    doc.fillColor('#1e293b').font('Helvetica-Bold').fontSize(11).text('Student Details', 50, 148);
    doc.font('Helvetica').fontSize(10)
       .text(`Name: ${record.studentName}   |   Register No: ${record.registerNo}   |   Department: ${record.department}`, 50, 162);

    const tableTop = 205;
    let hasCredits = false;
    let totalCredits = 0;
    (record.semesters || []).forEach(s => {
      if (s.credits > 0) {
        hasCredits = true;
        totalCredits += s.credits;
      }
    });

    doc.rect(40, tableTop, doc.page.width - 80, 20).fill('#1e1b4b');
    doc.fillColor('white').font('Helvetica-Bold').fontSize(10);
    
    if (hasCredits) {
      doc.text('Semester', 80, tableTop + 5);
      doc.text('Credits', 240, tableTop + 5);
      doc.text('GPA', 400, tableTop + 5);
    } else {
      doc.text('Semester', 80, tableTop + 5);
      doc.text('GPA', 400, tableTop + 5);
    }

    let y = tableTop + 20;
    (record.semesters || []).forEach((s, idx) => {
      doc.rect(40, y, doc.page.width - 80, 18).fill(idx % 2 === 0 ? '#f8fafc' : 'white');
      doc.fillColor('#1e293b').font('Helvetica').fontSize(10);
      
      if (hasCredits) {
        doc.text(String(s.semester), 80, y + 4);
        doc.text(String(s.credits || 0), 240, y + 4);
        doc.text(s.gpa.toFixed(2), 400, y + 4);
      } else {
        doc.text(String(s.semester), 80, y + 4);
        doc.text(s.gpa.toFixed(2), 400, y + 4);
      }
      y += 18;
    });

    if (hasCredits && totalCredits > 0) {
      doc.rect(40, y, doc.page.width - 80, 20).fill('#e0e7ff');
      doc.fillColor('#1e1b4b').font('Helvetica-Bold').fontSize(10)
         .text(`Total Credits: ${totalCredits}`, 80, y + 5);
      y += 20;
    }

    y += 15;
    const cx = doc.page.width / 2;
    doc.roundedRect(cx - 90, y, 180, 60, 8).fill('#1e1b4b');
    doc.fillColor('white').font('Helvetica').fontSize(12)
       .text('Cumulative CGPA', cx - 90, y + 8, { width: 180, align: 'center' });
    doc.font('Helvetica-Bold').fontSize(30).fillColor('#6ee7b7')
       .text(record.cgpa.toFixed(2), cx - 90, y + 26, { width: 180, align: 'center' });

    drawFooter(doc);
    doc.end();
  });
};

/* ─── Rank-list PDF ──────────────────────────────────────────────────────── */
const buildRankListPdf = (records, meta) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margins: { top: 40, bottom: 15, left: 40, right: 40 }, size: 'A4' });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    drawHeader(doc, meta.department, `${meta.type === 'GPA' ? 'GPA' : 'CGPA'} Rank List — Semester ${meta.semester || 'All'}`);

    const tableTop = 145;
    doc.rect(40, tableTop, doc.page.width - 80, 22).fill('#1e1b4b');
    doc.fillColor('white').font('Helvetica-Bold').fontSize(10);
    ['Rank', 'Register No', 'Student Name', meta.type === 'GPA' ? 'GPA' : 'CGPA']
      .forEach((h, i) => doc.text(h, [46, 90, 200, 460][i], tableTop + 6));

    let y = tableTop + 22;
    records.forEach((r, idx) => {
      const isTop = idx < 3;
      doc.rect(40, y, doc.page.width - 80, 20)
         .fill(isTop ? '#fef9c3' : (idx % 2 === 0 ? '#f8fafc' : 'white'));
      doc.fillColor(isTop ? '#92400e' : '#1e293b')
         .font(isTop ? 'Helvetica-Bold' : 'Helvetica').fontSize(10);
      const score = meta.type === 'GPA' ? r.gpa : r.cgpa;
      [idx + 1, r.registerNo, r.studentName, score?.toFixed(2)]
        .forEach((v, i) => doc.text(String(v ?? ''), [46, 90, 200, 460][i], y + 5));
      y += 20;
      if (y > doc.page.height - 80) { doc.addPage(); y = 40; }
    });

    drawFooter(doc);
    doc.end();
  });
};

/* ─── Batch GPA PDF (one page per student, NO blank pages) ───────────────── */
const buildBatchGpaPdf = (records, meta) => {
  return new Promise((resolve, reject) => {
    // Use autoFirstPage:true so pdfkit creates page-1 automatically.
    // We call addPage() only for records 2, 3, … to avoid the blank-page bug
    // that occurs when autoFirstPage:false is combined with explicit addPage().
    const doc = new PDFDocument({ margins: { top: 40, bottom: 15, left: 40, right: 40 }, size: 'A4' });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    records.forEach((record, rIdx) => {
      // Add a fresh page for every student after the first
      if (rIdx > 0) doc.addPage();

      // ── Page header ──
      doc.rect(0, 0, doc.page.width, 90).fill('#1e1b4b');
      doc.fillColor('white').font('Helvetica-Bold').fontSize(18)
         .text('RAMCO INSTITUTE OF TECHNOLOGY', 40, 18, { align: 'center' });
      doc.fontSize(10).font('Helvetica')
         .text('Rajapalayam, Virudhunagar District, Tamil Nadu', 40, 42, { align: 'center' });
      doc.fontSize(10)
         .text(`Department of ${record.department || 'Academic Affairs'} — Batch: ${meta.batchName}`, 40, 58, { align: 'center' })
         .text(`Semester GPA Report  |  Student ${rIdx + 1} of ${records.length}`, 40, 72, { align: 'center' });

      // ── Student info box ──
      doc.rect(40, 100, doc.page.width - 80, 55).fill('#f8fafc').stroke('#e2e8f0');
      doc.fillColor('#1e293b').font('Helvetica-Bold').fontSize(11).text('Student Details', 50, 108);
      doc.font('Helvetica').fontSize(10)
         .text(`Name: ${record.studentName}`, 50, 122)
         .text(`Register No: ${record.registerNo}`, 300, 122)
         .text(`Semester: ${record.semester}  |  Regulation: ${record.regulation || 'R2021'}`, 50, 136);

      // ── Subjects table ──
      const tableTop = 170;

      // Header row
      doc.rect(40, tableTop, doc.page.width - 80, ROW_H).fill('#1e1b4b');
      doc.fillColor('white').font('Helvetica-Bold').fontSize(9);
      TABLE_HEADERS.forEach((h, i) =>
        doc.text(h, TABLE_COLS[i] + 3, tableTop + 7, { width: TABLE_COL_W[i], lineBreak: false })
      );

      // Data rows — only show subjects where a real grade was given
      let y = tableTop + ROW_H;
      let totalCredits = 0;
      const gradedSubjects = (record.subjects || []).filter(s => s.grade && s.grade.trim() !== '');
      gradedSubjects.forEach((s, idx) => {
        const bg = idx % 2 === 0 ? '#f8fafc' : 'white';
        doc.rect(40, y, doc.page.width - 80, ROW_H).fill(bg);
        doc.fillColor('#1e293b').font('Helvetica').fontSize(9);
        totalCredits += s.credits;
        const row = [idx + 1, s.subjectCode, s.subjectName, s.credits, s.grade];
        row.forEach((val, i) =>
          doc.text(String(val), TABLE_COLS[i] + 3, y + 7, { width: TABLE_COL_W[i], lineBreak: false })
        );
        y += ROW_H;
      });

      // ── Totals bar (Credits only) ──
      doc.rect(40, y, doc.page.width - 80, 22).fill('#e0e7ff');
      doc.fillColor('#1e1b4b').font('Helvetica-Bold').fontSize(10)
         .text(`Total Credits: ${totalCredits}`, 50, y + 6);
      y += 22;

      // ── GPA result badge ──
      y += 16;
      const cx = doc.page.width / 2;
      doc.roundedRect(cx - 80, y, 160, 58, 8).fill('#1e1b4b');
      doc.fillColor('white').font('Helvetica').fontSize(10)
         .text('Semester GPA', cx - 80, y + 9, { width: 160, align: 'center' });
      doc.font('Helvetica-Bold').fontSize(28).fillColor('#a5b4fc')
         .text(record.gpa.toFixed(2), cx - 80, y + 26, { width: 160, align: 'center' });

      // ── Page footer ──
      const fy = doc.page.height - 50;
      doc.save()
         .moveTo(40, fy).lineTo(doc.page.width - 40, fy)
         .strokeColor('#d1d5db').stroke().restore();
      doc.fillColor('#6b7280').fontSize(8)
         .text(
           `Batch: ${meta.batchName}  |  Generated by RIT CGPA Portal — ${new Date().toLocaleString('en-IN')}`,
           40, fy + 8, { align: 'center' }
         );
    });

    doc.end();
  });
};

module.exports = { buildGpaPdf, buildCgpaPdf, buildRankListPdf, buildBatchGpaPdf };
