"use node";

import { action } from "./_generated/server";
import { v } from "convex/values";
import { api } from "./_generated/api";

const PDFDocument = require("pdfkit");

/* ─── Shared header / footer helpers ──────────────────────────────────────── */

const drawHeader = (doc: any, department: string, title: string) => {
  doc.rect(0, 0, doc.page.width, 90).fill("#1e1b4b");
  doc.fillColor("white").font("Helvetica-Bold").fontSize(20)
     .text("RAMCO INSTITUTE OF TECHNOLOGY", 40, 20, { align: "center" });
  doc.fontSize(12).font("Helvetica")
     .text("Rajapalayam, Virudhunagar District, Tamil Nadu", 40, 46, { align: "center" });
  doc.fontSize(11)
     .text(`Department of ${department || "Academic Affairs"}`, 40, 62, { align: "center" });
  doc.fillColor("#1e1b4b").font("Helvetica-Bold").fontSize(15)
     .text(title, 40, 105, { align: "center", underline: true });
};

const drawFooter = (doc: any) => {
  const y = doc.page.height - 55;
  doc.save().moveTo(40, y).lineTo(doc.page.width - 40, y)
     .strokeColor("#d1d5db").stroke().restore();
  doc.fillColor("#6b7280").fontSize(9)
     .text(`Generated by RIT CGPA Portal — ${new Date().toLocaleString("en-IN")}`, 40, y + 10, { align: "center" });
};

const TABLE_COLS = [40, 68, 158, 378, 458];
const TABLE_COL_W = [26, 88, 218, 78, 94];
const TABLE_HEADERS = ["#", "Subject Code", "Subject Name", "Credits", "Grade"];
const ROW_H = 22;

/* ─── GPA PDF Builder ─── */
const buildGpaPdfBuffer = (record: any): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margins: { top: 40, bottom: 15, left: 40, right: 40 }, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    drawHeader(doc, record.department, "Semester GPA Report");

    doc.rect(40, 140, doc.page.width - 80, 60).fill("#f8fafc").stroke("#e2e8f0");
    doc.fillColor("#1e293b").font("Helvetica-Bold").fontSize(11).text("Student Details", 50, 148);
    doc.font("Helvetica").fontSize(10)
       .text(`Name: ${record.studentName}`, 50, 162)
       .text(`Register No: ${record.registerNo}`, 300, 162)
       .text(`Semester: ${record.semester}  |  Regulation: ${record.regulation || "R2021"}  |  Dept: ${record.department}`, 50, 176);

    const tableTop = 215;
    doc.rect(40, tableTop, doc.page.width - 80, ROW_H).fill("#1e1b4b");
    doc.fillColor("white").font("Helvetica-Bold").fontSize(9);
    TABLE_HEADERS.forEach((h, i) =>
      doc.text(h, TABLE_COLS[i] + 3, tableTop + 7, { width: TABLE_COL_W[i], lineBreak: false })
    );

    let y = tableTop + ROW_H;
    let totalCredits = 0;
    const gradedSubjects = (record.subjects || []).filter((s: any) => s.grade && s.grade.trim() !== "");
    gradedSubjects.forEach((s: any, idx: number) => {
      const bg = idx % 2 === 0 ? "#f8fafc" : "white";
      doc.rect(40, y, doc.page.width - 80, ROW_H).fill(bg);
      doc.fillColor("#1e293b").font("Helvetica").fontSize(9);
      totalCredits += s.credits;
      const row = [idx + 1, s.subjectCode, s.subjectName, s.credits, s.grade];
      row.forEach((val, i) =>
        doc.text(String(val), TABLE_COLS[i] + 3, y + 7, { width: TABLE_COL_W[i], lineBreak: false })
      );
      y += ROW_H;
    });

    doc.rect(40, y, doc.page.width - 80, 22).fill("#e0e7ff");
    doc.fillColor("#1e1b4b").font("Helvetica-Bold").fontSize(10)
       .text(`Total Credits: ${totalCredits}`, 50, y + 6);
    y += 22;

    y += 18;
    const cx = doc.page.width / 2;
    doc.roundedRect(cx - 80, y, 160, 58, 8).fill("#1e1b4b");
    doc.fillColor("white").font("Helvetica").fontSize(11)
       .text("Semester GPA", cx - 80, y + 9, { width: 160, align: "center" });
    doc.font("Helvetica-Bold").fontSize(28).fillColor("#a5b4fc")
       .text(record.gpa.toFixed(2), cx - 80, y + 26, { width: 160, align: "center" });

    drawFooter(doc);
    doc.end();
  });
};

/* ─── CGPA PDF Builder ─── */
const buildCgpaPdfBuffer = (record: any): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margins: { top: 40, bottom: 15, left: 40, right: 40 }, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    drawHeader(doc, record.department, "Cumulative CGPA Report");

    doc.rect(40, 140, doc.page.width - 80, 45).fill("#f8fafc").stroke("#e2e8f0");
    doc.fillColor("#1e293b").font("Helvetica-Bold").fontSize(11).text("Student Details", 50, 148);
    doc.font("Helvetica").fontSize(10)
       .text(`Name: ${record.studentName}   |   Register No: ${record.registerNo}   |   Department: ${record.department}`, 50, 162);

    const tableTop = 205;
    let hasCredits = false;
    let totalCredits = 0;
    (record.semesters || []).forEach((s: any) => {
      if (s.credits > 0) {
        hasCredits = true;
        totalCredits += s.credits;
      }
    });

    doc.rect(40, tableTop, doc.page.width - 80, 20).fill("#1e1b4b");
    doc.fillColor("white").font("Helvetica-Bold").fontSize(10);
    
    if (hasCredits) {
      doc.text("Semester", 80, tableTop + 5);
      doc.text("Credits", 240, tableTop + 5);
      doc.text("GPA", 400, tableTop + 5);
    } else {
      doc.text("Semester", 80, tableTop + 5);
      doc.text("GPA", 400, tableTop + 5);
    }

    let y = tableTop + 20;
    (record.semesters || []).forEach((s: any, idx: number) => {
      doc.rect(40, y, doc.page.width - 80, 18).fill(idx % 2 === 0 ? "#f8fafc" : "white");
      doc.fillColor("#1e293b").font("Helvetica").fontSize(10);
      
      if (hasCredits) {
        doc.text(String(s.semester), 80, y + 4);
        doc.text(String(s.credits || 0), 240, y + 4);
        doc.text(s.gpa.toFixed(2), 400, y + 4);
      } else {
        doc.text(String(s.semester), 80, y + 4);
        doc.text(s.gpa.toFixed(2), 400, y + 4);
      }
      y += 18;
    });

    if (hasCredits && totalCredits > 0) {
      doc.rect(40, y, doc.page.width - 80, 20).fill("#e0e7ff");
      doc.fillColor("#1e1b4b").font("Helvetica-Bold").fontSize(10)
         .text(`Total Credits: ${totalCredits}`, 80, y + 5);
      y += 20;
    }

    y += 15;
    const cx = doc.page.width / 2;
    doc.roundedRect(cx - 90, y, 180, 60, 8).fill("#1e1b4b");
    doc.fillColor("white").font("Helvetica").fontSize(12)
       .text("Cumulative CGPA", cx - 90, y + 8, { width: 180, align: "center" });
    doc.font("Helvetica-Bold").fontSize(30).fillColor("#6ee7b7")
       .text(record.cgpa.toFixed(2), cx - 90, y + 26, { width: 180, align: "center" });

    drawFooter(doc);
    doc.end();
  });
};

/* ─── Rank List PDF Builder ─── */
const buildRankListPdfBuffer = (records: any[], meta: any): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margins: { top: 40, bottom: 15, left: 40, right: 40 }, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    drawHeader(doc, meta.department, `${meta.type === "GPA" ? "GPA" : "CGPA"} Rank List — Semester ${meta.semester || "All"}`);

    const tableTop = 145;
    doc.rect(40, tableTop, doc.page.width - 80, 22).fill("#1e1b4b");
    doc.fillColor("white").font("Helvetica-Bold").fontSize(10);
    ["Rank", "Register No", "Student Name", meta.type === "GPA" ? "GPA" : "CGPA"]
      .forEach((h, i) => doc.text(h, [46, 90, 200, 460][i], tableTop + 6));

    let y = tableTop + 22;
    records.forEach((r, idx) => {
      const isTop = idx < 3;
      doc.rect(40, y, doc.page.width - 80, 20)
         .fill(isTop ? "#fef9c3" : (idx % 2 === 0 ? "#f8fafc" : "white"));
      doc.fillColor(isTop ? "#92400e" : "#1e293b")
         .font(isTop ? "Helvetica-Bold" : "Helvetica").fontSize(10);
      const score = meta.type === "GPA" ? r.gpa : r.cgpa;
      [idx + 1, r.registerNo, r.studentName, score?.toFixed(2)]
        .forEach((v, i) => doc.text(String(v ?? ""), [46, 90, 200, 460][i], y + 5));
      y += 20;
      if (y > doc.page.height - 80) { doc.addPage(); y = 40; }
    });

    drawFooter(doc);
    doc.end();
  });
};

/* ─── Batch GPA PDF Builder ─── */
const buildBatchGpaPdfBuffer = (records: any[], meta: any): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margins: { top: 40, bottom: 15, left: 40, right: 40 }, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    records.forEach((record, rIdx) => {
      if (rIdx > 0) doc.addPage();

      doc.rect(0, 0, doc.page.width, 90).fill("#1e1b4b");
      doc.fillColor("white").font("Helvetica-Bold").fontSize(18)
         .text("RAMCO INSTITUTE OF TECHNOLOGY", 40, 18, { align: "center" });
      doc.fontSize(10).font("Helvetica")
         .text("Rajapalayam, Virudhunagar District, Tamil Nadu", 40, 42, { align: "center" });
      doc.fontSize(10)
         .text(`Department of ${record.department || "Academic Affairs"} — Batch: ${meta.batchName}`, 40, 58, { align: "center" })
         .text(`Semester GPA Report  |  Student ${rIdx + 1} of ${records.length}`, 40, 72, { align: "center" });

      doc.rect(40, 100, doc.page.width - 80, 55).fill("#f8fafc").stroke("#e2e8f0");
      doc.fillColor("#1e293b").font("Helvetica-Bold").fontSize(11).text("Student Details", 50, 108);
      doc.font("Helvetica").fontSize(10)
         .text(`Name: ${record.studentName}`, 50, 122)
         .text(`Register No: ${record.registerNo}`, 300, 122)
         .text(`Semester: ${record.semester}  |  Regulation: ${record.regulation || "R2021"}`, 50, 136);

      const tableTop = 170;
      doc.rect(40, tableTop, doc.page.width - 80, ROW_H).fill("#1e1b4b");
      doc.fillColor("white").font("Helvetica-Bold").fontSize(9);
      TABLE_HEADERS.forEach((h, i) =>
        doc.text(h, TABLE_COLS[i] + 3, tableTop + 7, { width: TABLE_COL_W[i], lineBreak: false })
      );

      let y = tableTop + ROW_H;
      let totalCredits = 0;
      const gradedSubjects = (record.subjects || []).filter((s: any) => s.grade && s.grade.trim() !== "");
      gradedSubjects.forEach((s: any, idx: number) => {
        const bg = idx % 2 === 0 ? "#f8fafc" : "white";
        doc.rect(40, y, doc.page.width - 80, ROW_H).fill(bg);
        doc.fillColor("#1e293b").font("Helvetica").fontSize(9);
        totalCredits += s.credits;
        const row = [idx + 1, s.subjectCode, s.subjectName, s.credits, s.grade];
        row.forEach((val, i) =>
          doc.text(String(val), TABLE_COLS[i] + 3, y + 7, { width: TABLE_COL_W[i], lineBreak: false })
        );
        y += ROW_H;
      });

      doc.rect(40, y, doc.page.width - 80, 22).fill("#e0e7ff");
      doc.fillColor("#1e1b4b").font("Helvetica-Bold").fontSize(10)
         .text(`Total Credits: ${totalCredits}`, 50, y + 6);
      y += 22;

      y += 16;
      const cx = doc.page.width / 2;
      doc.roundedRect(cx - 80, y, 160, 58, 8).fill("#1e1b4b");
      doc.fillColor("white").font("Helvetica").fontSize(10)
         .text("Semester GPA", cx - 80, y + 9, { width: 160, align: "center" });
      doc.font("Helvetica-Bold").fontSize(28).fillColor("#a5b4fc")
         .text(record.gpa.toFixed(2), cx - 80, y + 26, { width: 160, align: "center" });

      const fy = doc.page.height - 50;
      doc.save()
         .moveTo(40, fy).lineTo(doc.page.width - 40, fy)
         .strokeColor("#d1d5db").stroke().restore();
      doc.fillColor("#6b7280").fontSize(8)
         .text(
           `Batch: ${meta.batchName}  |  Generated by RIT CGPA Portal — ${new Date().toLocaleString("en-IN")}`,
           40, fy + 8, { align: "center" }
         );
    });

    doc.end();
  });
};

/* ─── Convex Actions Exposing Base64 Downloads ─── */

export const generateGpaPdf = action({
  args: {
    studentName: v.string(),
    registerNo: v.string(),
    semester: v.number(),
    department: v.string(),
    regulation: v.string(),
    subjects: v.array(
      v.object({
        subjectCode: v.string(),
        subjectName: v.string(),
        credits: v.number(),
        grade: v.string(),
        gradePoint: v.number(),
      })
    ),
    totalCredits: v.number(),
    totalPoints: v.number(),
    gpa: v.number(),
  },
  handler: async (ctx, args) => {
    const buffer = await buildGpaPdfBuffer(args);
    return buffer.toString("base64");
  },
});

export const generateCgpaPdf = action({
  args: {
    studentName: v.string(),
    registerNo: v.string(),
    department: v.string(),
    regulation: v.string(),
    semesters: v.array(
      v.object({
        semester: v.number(),
        gpa: v.number(),
        credits: v.number(),
      })
    ),
    cgpa: v.number(),
  },
  handler: async (ctx, args) => {
    const buffer = await buildCgpaPdfBuffer(args);
    return buffer.toString("base64");
  },
});

export const generateStoredGpaPdf = action({
  args: { recordId: v.id("gpaRecords") },
  handler: async (ctx, args) => {
    const record = await ctx.runQuery(api.gpa.getRecords, {});
    const r = record.find((x: any) => x._id === args.recordId);
    if (!r) throw new Error("GPA record not found");

    const buffer = await buildGpaPdfBuffer(r);
    return buffer.toString("base64");
  },
});

export const generateStoredCgpaPdf = action({
  args: { recordId: v.id("cgpaRecords") },
  handler: async (ctx, args) => {
    const record = await ctx.runQuery(api.cgpa.getRecords, {});
    const r = record.find((x: any) => x._id === args.recordId);
    if (!r) throw new Error("CGPA record not found");

    const buffer = await buildCgpaPdfBuffer(r);
    return buffer.toString("base64");
  },
});

export const generateRankListGpaPdf = action({
  args: {
    department: v.string(),
    semester: v.number(),
  },
  handler: async (ctx, args) => {
    const records = await ctx.runQuery(api.gpa.getRecords, {
      department: args.department,
      semester: args.semester,
    });

    const sorted = [...records].sort((a: any, b: any) => b.gpa - a.gpa).slice(0, 100);

    const buffer = await buildRankListPdfBuffer(sorted, {
      department: args.department,
      semester: args.semester,
      type: "GPA",
    });
    return buffer.toString("base64");
  },
});

export const generateRankListCgpaPdf = action({
  args: {
    department: v.string(),
  },
  handler: async (ctx, args) => {
    const records = await ctx.runQuery(api.cgpa.getRecords, {
      department: args.department,
    });

    const sorted = [...records].sort((a: any, b: any) => b.cgpa - a.cgpa).slice(0, 100);

    const buffer = await buildRankListPdfBuffer(sorted, {
      department: args.department,
      type: "CGPA",
    });
    return buffer.toString("base64");
  },
});

export const generateBatchGpaPdf = action({
  args: { batchId: v.string() },
  handler: async (ctx, args) => {
    const records = await ctx.runQuery(api.gpa.getBatchRecords, { batchId: args.batchId });
    if (records.length === 0) throw new Error("Batch empty or not found");

    const batchName = records[0].batchName || args.batchId;
    const buffer = await buildBatchGpaPdfBuffer(records, { batchName });
    return buffer.toString("base64");
  },
});
