"use node";

import { action } from "./_generated/server";
import { v } from "convex/values";
import { api } from "./_generated/api";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

// ── A4 page dimensions (points) ────────────────────────────────────────────
const PW = 595.28;
const PH = 841.89;

// ── Colours (r,g,b in 0–1) ─────────────────────────────────────────────────
const C = {
  navy:        rgb(0.118, 0.106, 0.294), // #1e1b4b
  white:       rgb(1, 1, 1),
  dark:        rgb(0.118, 0.161, 0.231), // #1e293b
  lightBg:     rgb(0.973, 0.980, 0.988), // #f8fafc
  altBg:       rgb(1, 1, 1),
  purple:      rgb(0.878, 0.906, 1.000), // #e0e7ff
  periwinkle:  rgb(0.647, 0.706, 0.988), // #a5b4fc
  gray:        rgb(0.420, 0.447, 0.502), // #6b7280
  lineGray:    rgb(0.820, 0.835, 0.859), // #d1d5db
  teal:        rgb(0.431, 0.906, 0.718), // #6ee7b7
  yellowLight: rgb(0.996, 0.976, 0.765), // #fef9c3
  amber:       rgb(0.573, 0.251, 0.055), // #92400e
};

// ── Coordinate helper: convert pdfkit-style y (top-left) to pdf-lib (bottom-left)
const pY = (y: number, h: number = 0) => PH - y - h;

// ── Draw filled rectangle ──────────────────────────────────────────────────
function fillRect(page: any, x: number, y: number, w: number, h: number, color: any) {
  page.drawRectangle({ x, y: pY(y, h), width: w, height: h, color });
}

// ── Draw text at pdfkit-style coordinates ─────────────────────────────────
function txt(
  page: any,
  text: string,
  x: number,
  y: number,
  size: number,
  font: any,
  color: any = C.dark,
  maxWidth?: number,
  align: "left" | "center" = "left"
) {
  let drawX = x;
  const safe = String(text ?? "");
  if (align === "center" && maxWidth !== undefined) {
    const tw = font.widthOfTextAtSize(safe, size);
    drawX = x + Math.max(0, (maxWidth - tw) / 2);
  }
  page.drawText(safe, {
    x: drawX,
    y: pY(y, size * 0.75),
    size,
    font,
    color,
    maxWidth,
  });
}

// ── Shared header ──────────────────────────────────────────────────────────
async function drawHeader(page: any, bold: any, reg: any, dept: string, title: string) {
  fillRect(page, 0, 0, PW, 90, C.navy);
  txt(page, "RAMCO INSTITUTE OF TECHNOLOGY", 40, 20, 18, bold, C.white, PW - 80, "center");
  txt(page, "Rajapalayam, Virudhunagar District, Tamil Nadu", 40, 44, 10, reg, C.white, PW - 80, "center");
  txt(page, `Department of ${dept || "Academic Affairs"}`, 40, 60, 10, reg, C.white, PW - 80, "center");
  txt(page, title, 40, 106, 13, bold, C.navy, PW - 80, "center");
}

// ── Shared footer ──────────────────────────────────────────────────────────
function drawFooter(page: any, reg: any) {
  const fy = PH - 55;
  page.drawLine({ start: { x: 40, y: fy }, end: { x: PW - 40, y: fy }, thickness: 0.5, color: C.lineGray });
  txt(page, `Generated by RIT CGPA Portal — ${new Date().toLocaleString("en-IN")}`, 40, PH - 44, 8, reg, C.gray, PW - 80, "center");
}

// ── Table column layout (same as before) ──────────────────────────────────
const TCOLS = [40, 68, 158, 378, 458];
const TWIDTHS = [26, 88, 218, 78, 94];
const THEADERS = ["#", "Subject Code", "Subject Name", "Credits", "Grade"];
const ROW_H = 22;

// ══════════════════════════════════════════════════════════════════════════
// GPA PDF builder
// ══════════════════════════════════════════════════════════════════════════
async function buildGpaPdf(record: any): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const reg  = await doc.embedFont(StandardFonts.Helvetica);
  const page = doc.addPage([PW, PH]);

  await drawHeader(page, bold, reg, record.department, "Semester GPA Report");

  // Student info box
  fillRect(page, 40, 140, PW - 80, 55, C.lightBg);
  txt(page, "Student Details",        50, 148, 11, bold);
  txt(page, `Name: ${record.studentName}`,  50, 162, 10, reg);
  txt(page, `Register No: ${record.registerNo}`, 300, 162, 10, reg);
  txt(page, `Department: ${record.department}  |  Regulation: ${record.regulation || "R2021"}`, 50, 176, 9, reg);

  // Table header for Semester GPAs
  const tableTop = 210;
  fillRect(page, 40, tableTop, PW - 80, ROW_H, C.navy);
  txt(page, "#", 55, tableTop + 7, 9, bold, C.white, 30);
  txt(page, "Semester", 110, tableTop + 7, 9, bold, C.white, 150);
  txt(page, "Credits Earned", 280, tableTop + 7, 9, bold, C.white, 120);
  txt(page, "Semester GPA", 430, tableTop + 7, 9, bold, C.white, 110);

  // Data rows
  let y = tableTop + ROW_H;
  let totalCredits = 0;
  const semesters: any[] = record.semesters && record.semesters.length > 0
    ? record.semesters
    : [{ semester: record.semester || 1, gpa: record.gpa || 0, credits: record.totalCredits || 0 }];

  semesters.forEach((s: any, idx: number) => {
    const bg = idx % 2 === 0 ? C.lightBg : C.altBg;
    fillRect(page, 40, y, PW - 80, ROW_H, bg);
    totalCredits += Number(s.credits) || 0;
    txt(page, String(idx + 1), 55, y + 7, 9, reg, C.dark, 30);
    txt(page, `Semester ${s.semester}`, 110, y + 7, 9, reg, C.dark, 150);
    txt(page, s.credits ? String(s.credits) : "N/A", 280, y + 7, 9, reg, C.dark, 120);
    txt(page, (Number(s.gpa) || 0).toFixed(2), 430, y + 7, 9, bold, C.dark, 110);
    y += ROW_H;
  });

  // Totals bar
  if (totalCredits > 0) {
    fillRect(page, 40, y, PW - 80, 22, C.purple);
    txt(page, `Total Credits: ${totalCredits}`, 50, y + 6, 10, bold, C.navy);
  }

  drawFooter(page, reg);
  return doc.save();
}

async function buildMultiStudentGpaPdf(studentList: any[]): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const reg  = await doc.embedFont(StandardFonts.Helvetica);

  for (const record of studentList) {
    const page = doc.addPage([PW, PH]);

    await drawHeader(page, bold, reg, record.department, "Semester GPA Report");

    // Student info box
    fillRect(page, 40, 140, PW - 80, 55, C.lightBg);
    txt(page, "Student Details", 50, 148, 11, bold);
    txt(page, `Name: ${record.studentName}`, 50, 162, 10, reg);
    txt(page, `Register No: ${record.registerNo}`, 300, 162, 10, reg);
    txt(page, `Department: ${record.department}  |  Regulation: ${record.regulation || "R2021"}`, 50, 176, 9, reg);

    // Table header for Semester GPAs
    const tableTop = 210;
    fillRect(page, 40, tableTop, PW - 80, ROW_H, C.navy);
    txt(page, "#", 55, tableTop + 7, 9, bold, C.white, 30);
    txt(page, "Semester", 110, tableTop + 7, 9, bold, C.white, 150);
    txt(page, "Credits Earned", 280, tableTop + 7, 9, bold, C.white, 120);
    txt(page, "Semester GPA", 430, tableTop + 7, 9, bold, C.white, 110);

    // Data rows
    let y = tableTop + ROW_H;
    let totalCredits = 0;
    const semesters: any[] = record.semesters && record.semesters.length > 0
      ? record.semesters
      : [{ semester: record.semester || 1, gpa: record.gpa || 0, credits: record.totalCredits || 0 }];

    semesters.forEach((s: any, idx: number) => {
      const bg = idx % 2 === 0 ? C.lightBg : C.altBg;
      fillRect(page, 40, y, PW - 80, ROW_H, bg);
      totalCredits += Number(s.credits) || 0;
      txt(page, String(idx + 1), 55, y + 7, 9, reg, C.dark, 30);
      txt(page, `Semester ${s.semester}`, 110, y + 7, 9, reg, C.dark, 150);
      txt(page, s.credits ? String(s.credits) : "N/A", 280, y + 7, 9, reg, C.dark, 120);
      txt(page, (Number(s.gpa) || 0).toFixed(2), 430, y + 7, 9, bold, C.dark, 110);
      y += ROW_H;
    });

    // Totals bar
    if (totalCredits > 0) {
      fillRect(page, 40, y, PW - 80, 22, C.purple);
      txt(page, `Total Credits: ${totalCredits}`, 50, y + 6, 10, bold, C.navy);
    }

    drawFooter(page, reg);
  }

  return doc.save();
}

// ══════════════════════════════════════════════════════════════════════════
// CGPA PDF builder
// ══════════════════════════════════════════════════════════════════════════
async function buildCgpaPdf(record: any): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const reg  = await doc.embedFont(StandardFonts.Helvetica);
  const page = doc.addPage([PW, PH]);

  await drawHeader(page, bold, reg, record.department, "Cumulative CGPA Report");

  fillRect(page, 40, 140, PW - 80, 45, C.lightBg);
  txt(page, "Student Details", 50, 148, 11, bold);
  txt(page, `Name: ${record.studentName}   |   Reg No: ${record.registerNo}   |   Dept: ${record.department}`, 50, 162, 9, reg);

  const semesters: any[] = record.semesters || [];
  const hasCredits = semesters.some((s: any) => (s.credits || 0) > 0);
  const tableTop = 205;

  fillRect(page, 40, tableTop, PW - 80, 20, C.navy);
  txt(page, "Semester", 80, tableTop + 5, 10, bold, C.white);
  if (hasCredits) txt(page, "Credits", 240, tableTop + 5, 10, bold, C.white);
  txt(page, "GPA", 400, tableTop + 5, 10, bold, C.white);

  let y = tableTop + 20;
  let totalCredits = 0;
  semesters.forEach((s: any, idx: number) => {
    const bg = idx % 2 === 0 ? C.lightBg : C.altBg;
    fillRect(page, 40, y, PW - 80, 18, bg);
    txt(page, String(s.semester), 80, y + 4, 10, reg);
    if (hasCredits) {
      txt(page, String(s.credits || 0), 240, y + 4, 10, reg);
      totalCredits += Number(s.credits) || 0;
    }
    txt(page, (Number(s.gpa) || 0).toFixed(2), 400, y + 4, 10, reg);
    y += 18;
  });

  if (hasCredits && totalCredits > 0) {
    fillRect(page, 40, y, PW - 80, 20, C.purple);
    txt(page, `Total Credits: ${totalCredits}`, 80, y + 5, 10, bold, C.navy);
    y += 20;
  }
  y += 15;

  const cx = PW / 2;
  fillRect(page, cx - 90, y, 180, 60, C.navy);
  txt(page, "Cumulative CGPA", cx - 90, y + 9, 11, reg, C.white, 180, "center");
  txt(page, (Number(record.cgpa) || 0).toFixed(2), cx - 90, y + 26, 26, bold, C.teal, 180, "center");

  drawFooter(page, reg);
  return doc.save();
}

// ══════════════════════════════════════════════════════════════════════════
// Rank-list PDF builder
// ══════════════════════════════════════════════════════════════════════════
async function buildRankListPdf(records: any[], meta: any): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const reg  = await doc.embedFont(StandardFonts.Helvetica);
  let page = doc.addPage([PW, PH]);

  const label = meta.type === "GPA" ? "GPA" : "CGPA";
  await drawHeader(page, bold, reg, meta.department, `${label} Rank List — Semester ${meta.semester || "All"}`);

  const tableTop = 145;
  fillRect(page, 40, tableTop, PW - 80, 22, C.navy);
  ["Rank", "Register No", "Student Name", label].forEach((h, i) =>
    txt(page, h, [46, 90, 200, 460][i], tableTop + 6, 10, bold, C.white)
  );

  let y = tableTop + 22;
  records.forEach((r: any, idx: number) => {
    const isTop = idx < 3;
    const bg = isTop ? C.yellowLight : (idx % 2 === 0 ? C.lightBg : C.altBg);
    const textColor = isTop ? C.amber : C.dark;
    const f = isTop ? bold : reg;
    if (y > PH - 80) {
      page = doc.addPage([PW, PH]);
      y = 40;
    }
    fillRect(page, 40, y, PW - 80, 20, bg);
    const score = meta.type === "GPA" ? r.gpa : r.cgpa;
    [idx + 1, r.registerNo, r.studentName, (Number(score) || 0).toFixed(2)].forEach((v, i) =>
      txt(page, String(v ?? ""), [46, 90, 200, 460][i], y + 5, 10, f, textColor)
    );
    y += 20;
  });

  drawFooter(page, reg);
  return doc.save();
}

// ══════════════════════════════════════════════════════════════════════════
// Batch GPA PDF builder (one page per student)
// ══════════════════════════════════════════════════════════════════════════
async function buildBatchGpaPdf(records: any[], meta: any): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const reg  = await doc.embedFont(StandardFonts.Helvetica);

  for (let rIdx = 0; rIdx < records.length; rIdx++) {
    const record = records[rIdx];
    const page = doc.addPage([PW, PH]);

    fillRect(page, 0, 0, PW, 90, C.navy);
    txt(page, "RAMCO INSTITUTE OF TECHNOLOGY", 40, 18, 16, bold, C.white, PW - 80, "center");
    txt(page, "Rajapalayam, Virudhunagar District, Tamil Nadu", 40, 40, 9, reg, C.white, PW - 80, "center");
    txt(page, `Department of ${record.department || "Academic Affairs"} — Batch: ${meta.batchName}`, 40, 56, 9, reg, C.white, PW - 80, "center");
    txt(page, `Semester GPA Report  |  Student ${rIdx + 1} of ${records.length}`, 40, 70, 9, reg, C.white, PW - 80, "center");

    fillRect(page, 40, 100, PW - 80, 55, C.lightBg);
    txt(page, "Student Details",             50, 108, 11, bold);
    txt(page, `Name: ${record.studentName}`, 50, 122, 10, reg);
    txt(page, `Register No: ${record.registerNo}`, 300, 122, 10, reg);
    txt(page, `Semester: ${record.semester}  |  Regulation: ${record.regulation || "R2021"}`, 50, 136, 9, reg);

    const tableTop = 170;
    fillRect(page, 40, tableTop, PW - 80, ROW_H, C.navy);
    txt(page, "#", 55, tableTop + 7, 9, bold, C.white, 30);
    txt(page, "Semester", 110, tableTop + 7, 9, bold, C.white, 150);
    txt(page, "Credits Earned", 280, tableTop + 7, 9, bold, C.white, 120);
    txt(page, "Semester GPA", 430, tableTop + 7, 9, bold, C.white, 110);

    let y = tableTop + ROW_H;
    let totalCredits = 0;
    const semesters: any[] = record.semesters && record.semesters.length > 0
      ? record.semesters
      : [{ semester: record.semester || 1, gpa: record.gpa || 0, credits: record.totalCredits || 0 }];

    semesters.forEach((s: any, idx: number) => {
      const bg = idx % 2 === 0 ? C.lightBg : C.altBg;
      fillRect(page, 40, y, PW - 80, ROW_H, bg);
      totalCredits += Number(s.credits) || 0;
      txt(page, String(idx + 1), 55, y + 7, 9, reg, C.dark, 30);
      txt(page, `Semester ${s.semester}`, 110, y + 7, 9, reg, C.dark, 150);
      txt(page, s.credits ? String(s.credits) : "N/A", 280, y + 7, 9, reg, C.dark, 120);
      txt(page, (Number(s.gpa) || 0).toFixed(2), 430, y + 7, 9, bold, C.dark, 110);
      y += ROW_H;
    });

    if (totalCredits > 0) {
      fillRect(page, 40, y, PW - 80, 22, C.purple);
      txt(page, `Total Credits: ${totalCredits}`, 50, y + 6, 10, bold, C.navy);
      y += 22;
    }
    y += 16;

    const cx = PW / 2;
    fillRect(page, cx - 80, y, 160, 58, C.navy);
    txt(page, "Semester GPA", cx - 80, y + 10, 10, reg, C.white, 160, "center");
    txt(page, (Number(record.gpa) || 0).toFixed(2), cx - 80, y + 26, 26, bold, C.periwinkle, 160, "center");

    const fy = PH - 50;
    page.drawLine({ start: { x: 40, y: fy }, end: { x: PW - 40, y: fy }, thickness: 0.5, color: C.lineGray });
    txt(page, `Batch: ${meta.batchName}  |  Generated by RIT CGPA Portal — ${new Date().toLocaleString("en-IN")}`, 40, PH - 42, 8, reg, C.gray, PW - 80, "center");
  }

  return doc.save();
}

// ══════════════════════════════════════════════════════════════════════════
// Default grade map (fallback when gradePoint not in record)
// ══════════════════════════════════════════════════════════════════════════
const DEFAULT_GP: Record<string, number> = {
  O: 10, "A+": 9, A: 8, "B+": 7, B: 6, C: 5, U: 0, RA: 0,
};

// ══════════════════════════════════════════════════════════════════════════
// Convex actions
// ══════════════════════════════════════════════════════════════════════════

// 1. Public GPA PDF (no auth, all fields optional — computed server-side)
export const generateGpaPdf = action({
  args: {
    studentName:  v.optional(v.string()),
    registerNo:   v.optional(v.string()),
    semester:     v.number(),
    department:   v.string(),
    regulation:   v.optional(v.string()),
    subjects: v.array(v.object({
      subjectCode:  v.string(),
      subjectName:  v.string(),
      credits:      v.number(),
      grade:        v.string(),
      gradePoint:   v.optional(v.number()),
    })),
    totalCredits: v.optional(v.number()),
    totalPoints:  v.optional(v.number()),
    gpa:          v.optional(v.number()),
  },
  handler: async (_ctx, args) => {
    const subjects = args.subjects.map((s) => ({
      ...s,
      gradePoint: s.gradePoint ?? DEFAULT_GP[s.grade.trim().toUpperCase()] ?? 0,
    }));
    let totalCredits = args.totalCredits ?? 0;
    let totalPoints  = args.totalPoints  ?? 0;
    if (args.totalCredits === undefined) {
      totalCredits = 0; totalPoints = 0;
      for (const s of subjects) { totalCredits += s.credits; totalPoints += s.credits * s.gradePoint; }
    }
    const gpa = args.gpa ?? (totalCredits > 0 ? parseFloat((totalPoints / totalCredits).toFixed(2)) : 0);
    const bytes = await buildGpaPdf({
      studentName: args.studentName || "ANONYMOUS",
      registerNo:  args.registerNo  || "N/A",
      semester: args.semester, department: args.department,
      regulation: args.regulation || "R2021",
      subjects, totalCredits, totalPoints, gpa,
    });
    return Buffer.from(bytes).toString("base64");
  },
});

// 2. Public CGPA PDF
export const generateCgpaPdf = action({
  args: {
    studentName: v.optional(v.string()),
    registerNo:  v.optional(v.string()),
    department:  v.string(),
    regulation:  v.optional(v.string()),
    semesters: v.array(v.object({
      semester: v.number(),
      gpa:      v.number(),
      credits:  v.optional(v.number()),
    })),
    cgpa: v.optional(v.number()),
  },
  handler: async (_ctx, args) => {
    const semesters = args.semesters.map((s) => ({ ...s, credits: s.credits ?? 0 }));
    let sum = 0, n = 0;
    for (const s of semesters) { if (s.gpa > 0) { sum += s.gpa; n++; } }
    const cgpa = args.cgpa ?? (n > 0 ? parseFloat((sum / n).toFixed(2)) : 0);
    const bytes = await buildCgpaPdf({
      studentName: args.studentName || "ANONYMOUS",
      registerNo:  args.registerNo  || "N/A",
      department: args.department,
      regulation: args.regulation || "R2021",
      semesters, cgpa,
    });
    return Buffer.from(bytes).toString("base64");
  },
});

// 3. Stored GPA record PDF (fetch by ID then generate)
export const generateStoredGpaPdf = action({
  args: { recordId: v.id("gpaRecords") },
  handler: async (ctx, args) => {
    const r = await ctx.runQuery(api.gpa.getById, { id: args.recordId });
    if (!r) throw new Error("GPA record not found");
    const cgpaRec = await ctx.runQuery(api.cgpa.getByRegNo, { registerNo: r.registerNo, department: r.department });
    const semesters = cgpaRec?.semesters && cgpaRec.semesters.length > 0
      ? cgpaRec.semesters
      : [{ semester: r.semester, gpa: r.gpa, credits: r.totalCredits || 0 }];
    const bytes = await buildGpaPdf({
      studentName: r.studentName,
      registerNo: r.registerNo,
      department: r.department,
      regulation: r.regulation || "R2021",
      semester: r.semester,
      gpa: r.gpa,
      semesters,
      cgpa: cgpaRec?.cgpa || r.gpa,
    });
    return Buffer.from(bytes).toString("base64");
  },
});

// 4. Stored CGPA record PDF
export const generateStoredCgpaPdf = action({
  args: { recordId: v.id("cgpaRecords") },
  handler: async (ctx, args) => {
    const r = await ctx.runQuery(api.cgpa.getById, { id: args.recordId });
    if (!r) throw new Error("CGPA record not found");
    const bytes = await buildCgpaPdf(r);
    return Buffer.from(bytes).toString("base64");
  },
});

// 5. GPA Rank List PDF
export const generateRankListGpaPdf = action({
  args: { department: v.string(), semester: v.number() },
  handler: async (ctx, args) => {
    const students = await ctx.runQuery(api.students.get, { department: args.department });
    const studentRegs = new Set(students.map((s: any) => s.registerNo.trim().toUpperCase()));
    const records = await ctx.runQuery(api.gpa.getRecords, { department: args.department, semester: args.semester });
    const valid = records.filter((r: any) => studentRegs.has(r.registerNo.trim().toUpperCase()));
    const sorted = [...valid].sort((a: any, b: any) => b.gpa - a.gpa).slice(0, 100);
    const bytes = await buildRankListPdf(sorted, { department: args.department, semester: args.semester, type: "GPA" });
    return Buffer.from(bytes).toString("base64");
  },
});

// 6. CGPA Rank List PDF
export const generateRankListCgpaPdf = action({
  args: { department: v.string() },
  handler: async (ctx, args) => {
    const students = await ctx.runQuery(api.students.get, { department: args.department });
    const studentRegs = new Set(students.map((s: any) => s.registerNo.trim().toUpperCase()));
    const records = await ctx.runQuery(api.cgpa.getRecords, { department: args.department });
    const valid = records.filter((r: any) => studentRegs.has(r.registerNo.trim().toUpperCase()) && r.cgpa > 0);
    const sorted = [...valid].sort((a: any, b: any) => b.cgpa - a.cgpa).slice(0, 100);
    const bytes = await buildRankListPdf(sorted, { department: args.department, type: "CGPA" });
    return Buffer.from(bytes).toString("base64");
  },
});

// 7. Batch GPA PDF
export const generateBatchGpaPdf = action({
  args: { batchId: v.string() },
  handler: async (ctx, args) => {
    const records = await ctx.runQuery(api.gpa.getBatchRecords, { batchId: args.batchId });
    if (records.length === 0) throw new Error("Batch empty or not found");
    const students = await ctx.runQuery(api.students.get, {});
    const studentRegs = new Set(students.map((s: any) => s.registerNo.trim().toUpperCase()));
    const validRecords = records.filter((r: any) => studentRegs.has(r.registerNo.trim().toUpperCase()));
    const recordsToUse = validRecords.length > 0 ? validRecords : records;
    const batchName = (recordsToUse[0] as any).batchName || args.batchId;
    const bytes = await buildBatchGpaPdf(recordsToUse, { batchName });
    return Buffer.from(bytes).toString("base64");
  },
});

// 8. Overall Semester GPA PDF
export const generateOverallSemesterGpaPdf = action({
  args: {
    department: v.optional(v.string()),
    semester: v.optional(v.number()),
    registerNos: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    const students = await ctx.runQuery(api.students.get, { department: args.department });
    const studentRegs = new Set(students.map((s: any) => s.registerNo.trim().toUpperCase()));
    const studentMap = new Map<string, string>();
    students.forEach((s: any) => studentMap.set(s.registerNo.trim().toUpperCase(), s.name));

    const records = await ctx.runQuery(api.gpa.getRecords, { department: args.department, semester: args.semester });

    let filterRegs: Set<string> | null = null;
    if (args.registerNos && args.registerNos.length > 0) {
      filterRegs = new Set(args.registerNos.map((r) => r.trim().toUpperCase()));
    }

    const validRecords = records.filter((r: any) => {
      const regUpper = r.registerNo.trim().toUpperCase();
      if (!studentRegs.has(regUpper)) return false;
      if (filterRegs && !filterRegs.has(regUpper)) return false;
      return r.gpa > 0;
    });

    const sortedRegs = Array.from(new Set(validRecords.map((r: any) => r.registerNo.trim().toUpperCase()))).sort();

    const studentList: any[] = [];
    for (const regNo of sortedRegs) {
      const sName = studentMap.get(regNo) || "Student";
      const history = await ctx.runQuery(api.cgpa.getStudentGpaHistory, { registerNo: regNo, department: args.department });
      
      let sDept = args.department || "IT";
      let sReg = "R2021";
      const matchingRec = validRecords.find((r: any) => r.registerNo.trim().toUpperCase() === regNo);
      if (matchingRec) {
        sDept = matchingRec.department || sDept;
        sReg = matchingRec.regulation || sReg;
      }

      studentList.push({
        studentName: sName,
        registerNo: regNo,
        department: sDept,
        regulation: sReg,
        semesters: history && history.length > 0 ? history : matchingRec ? [{ semester: matchingRec.semester, gpa: matchingRec.gpa, credits: matchingRec.totalCredits || 0 }] : [],
      });
    }

    if (studentList.length === 0) throw new Error("No GPA records found for the selected students.");
    const bytes = await buildMultiStudentGpaPdf(studentList);
    return Buffer.from(bytes).toString("base64");
  },
});

// 9. Overall CGPA PDF
export const generateOverallCgpaPdf = action({
  args: {
    department: v.optional(v.string()),
    registerNos: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    const students = await ctx.runQuery(api.students.get, { department: args.department });
    const studentRegs = new Set(students.map((s: any) => s.registerNo.trim().toUpperCase()));
    const studentMap = new Map<string, string>();
    students.forEach((s: any) => studentMap.set(s.registerNo.trim().toUpperCase(), s.name));

    const records = await ctx.runQuery(api.cgpa.getRecords, { department: args.department });

    let filterRegs: Set<string> | null = null;
    if (args.registerNos && args.registerNos.length > 0) {
      filterRegs = new Set(args.registerNos.map((r) => r.trim().toUpperCase()));
    }

    const validRecords = records
      .filter((r: any) => {
        const regUpper = r.registerNo.trim().toUpperCase();
        if (!studentRegs.has(regUpper)) return false;
        if (filterRegs && !filterRegs.has(regUpper)) return false;
        return r.cgpa > 0 || (r.semesters && r.semesters.length > 0);
      })
      .map((r: any) => ({
        ...r,
        studentName: studentMap.get(r.registerNo.trim().toUpperCase()) || r.studentName,
      }));

    if (validRecords.length === 0) throw new Error("No CGPA records found for the selected students.");
    const sorted = [...validRecords].sort((a: any, b: any) => a.registerNo.localeCompare(b.registerNo));
    const bytes = await buildRankListPdf(sorted, { department: args.department || "All Departments", type: "CGPA" });
    return Buffer.from(bytes).toString("base64");
  },
});

